Change spelling of CDT.cloud to CDT Cloud
eclipse-cdt-cloud/cdt-cloud pull request #25
Opened 2022-11-25 09:31 UTC by planger

2023-02-16 16:42 UTC, sdirix requested changes
Found one small issue

2023-02-16 16:42 UTC, sdirix commented on NOTICE.md
> +* Project home: https://projects.eclipse.org/projects/ecd.CDT Cloud
```suggestion
* Project home: https://projects.eclipse.org/projects/ecd.cdt-cloud
```

2023-02-16 19:01 UTC, planger commented
Thank you, I committed your suggestion!

2023-02-17 06:45 UTC, sdirix approved these changes
LGTM

2023-02-17 08:19 UTC, merged